# .github/workflows/seleniumbase-gitlab.yml
name: SeleniumBase GitLab Automation

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  automation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install Chrome and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4

        # Download and install Chrome using the current recommended method
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

        # Verify Chrome installation
        google-chrome --version
        
        # Clean up
        rm google-chrome-stable_current_amd64.deb
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run automation
      run: |
        # Start Xvfb with explicit error handling
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 3  # Wait for Xvfb to start
        
        # Verify Xvfb is running
        if ! ps aux | grep -q "[X]vfb :99"; then
          echo "Error: Xvfb failed to start"
          exit 1
        fi
        export DISPLAY=:99
        python main.py
      
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots
        path: |
          *.png
        retention-days: 90
        compression-level: 6
        overwrite: true
